[package]
name = "clock"
version = "0.1.0"
edition = "2021"


[dependencies]
time = { version = "0.3", features = ["local-offset", "parsing", "formatting"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
